language: perl
sudo: required

perl:
  - "5.26"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

services:
  - docker
  - mysql

cache:
  directories:
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/lib/site_perl/
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/bin/

env:
  - DYNAMODB_LOCAL="http://localhost:7777"

before_install:
  - docker pull tray/dynamodb-local
  - docker run -d -p 7777:7777 tray/dynamodb-local -inMemory -port 7777
  - docker ps -a
  - sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf

install:
  - cpanm --notest --quiet Dist::Zilla
  - cpanm DBD::mysql@4.033
  - cpanm --notest Test::mysqld@0.21
  - cpanm --notest DBIx::Class::InflateColumn::Serializer
  - cpanm --notest Net::EmptyPort
  - cpanm --notest DBIx::Class::Schema::Loader
  - cpanm --notest DateTime::Format::SQLite
  - cpanm --notest DateTime::Format::MySQL
  - cpanm --notest SQL::Translator
  - cpanm --notest Paws
  - cpanm --notest JSON
  - cpanm --notest MIME::Base64
  - cpanm --notest Compress::Zlib
  - dzil authordeps | cpanm --quiet --notest
  - cpanm --quiet --notest --installdeps .

script:
  - dzil test
